// <auto-generated />
using Mango.Services.ProductAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mango.Services.ProductAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mango.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryName = "Fruit",
                            Description = "description",
                            ImageUrl = "haidgsfghdfj",
                            Name = "Bananas",
                            Price = 10
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryName = "Fruit",
                            Description = "description",
                            ImageUrl = "haidgsfghdfj",
                            Name = "Peras",
                            Price = 12
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryName = "Fruit",
                            Description = "description",
                            ImageUrl = "haidgsfghdfj",
                            Name = "Apples",
                            Price = 8
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryName = "Bakery",
                            Description = "description",
                            ImageUrl = "haidgsfghdfj",
                            Name = "Bread",
                            Price = 5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
